### ISSUE TITLE
DPFServerException error after installing ANSYS2024 R1 on Linux

### ISSUE THREAD

**Issue by aukselis-c1connections** [ansys/pydpf-core#1446]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Running example model with ANSYS2024 R1 gives `ansys.dpf.gate.errors.DPFServerException: ResultInfoProvider:2<-Data sources not defined` error while using the same environment to do that with ANSYS2023 R1 works without any issues

```
DPF Server: {'server_ip': '', 'server_port': None, 'server_process_id': 2234620, 'server_version': '7.1', 'os': 'posix'}
Traceback (most recent call last):
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/errors.py", line 101, in wrapper
    out = func(*args, **kwargs)
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 504, in result_info
    self._cache_result_info()
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 282, in _cache_result_info
    self._result_info = self._load_result_info()
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 429, in _load_result_info
    raise e
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 423, in _load_result_info
    result_info = op.get_output(0, types.result_info)
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/dpf_operator.py", line 494, in get_output
    parameters = {type_tuple[2]: type_tuple[1](self, pin)}
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/gate/generated/operator_capi.py", line 588, in operator_getoutput_result_info
    raise errors.DPFServerException(sError.value)
ansys.dpf.gate.errors.DPFServerException: ResultInfoProvider:2<-Data sources not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ansys/Desktop/test.py", line 12, in <module>
    print(model)
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 203, in __str__
    txt += str(self.results)
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 157, in results
    self.metadata.result_info,
  File "/home/ansys/.local/lib/python3.9/site-packages/ansys/dpf/core/errors.py", line 106, in wrapper
    raise DPFServerException(details)
ansys.dpf.gate.errors.DPFServerException: ResultInfoProvider:2<-Data sources not defined

```

### Steps To Reproduce

```
from ansys.dpf.core import Model
from ansys.dpf.core import examples

from ansys.dpf import core as dpf

# start a server with entry capabilities
server = dpf.start_local_server(
    ansys_path="/ansys_inc/v241/"
)
print(server)

model = Model(examples.find_simple_bar(),server=server)
print(model)
```

### Which Operating System causes the issue?

Linux

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.9

### Installed packages

Package                               Version
------------------------------------- ------------
ansys-api-mapdl                       0.5.1
ansys-api-platform-instancemanagement 1.0.0
ansys-dpf-core                        0.10.0
ansys-mapdl-core                      0.65.0
ansys-mapdl-reader                    0.53.0
ansys-platform-instancemanagement     1.1.2
ansys-tools-path                      0.4.0
appdirs                               1.4.4
cachetools                            5.3.3
certifi                               2024.2.2
charset-normalizer                    3.3.2
click                                 8.1.7
contourpy                             1.2.0
cycler                                0.12.1
fonttools                             4.45.1
google-api-core                       2.17.1
google-api-python-client              2.119.0
google-auth                           2.28.1
google-auth-httplib2                  0.2.0
googleapis-common-protos              1.62.0
grpcio                                1.62.0
httplib2                              0.22.0
idna                                  3.6
imageio                               2.33.0
importlib-metadata                    7.0.1
importlib-resources                   6.1.1
kiwisolver                            1.4.5
matplotlib                            3.7.4
numpy                                 1.26.4
packaging                             23.2
pandas                                2.1.3
pexpect                               4.9.0
Pillow                                10.1.0
pip                                   23.3.1
platformdirs                          4.0.0
pooch                                 1.8.0
protobuf                              4.25.3
psutil                                5.9.8
ptyprocess                            0.7.0
pyansys-tools-versioning              0.5.0
pyasn1                                0.5.1
pyasn1-modules                        0.3.0
pyiges                                0.3.1
pyparsing                             3.1.1
python-dateutil                       2.8.2
pytz                                  2023.3.post1
pyvista                               0.38.6
PyYAML                                6.0.1
requests                              2.31.0
rsa                                   4.9
scipy                                 1.10.1
scooby                                0.9.2
setuptools                            69.1.1
six                                   1.16.0
tqdm                                  4.66.2
tzdata                                2023.3
uritemplate                           4.1.1
urllib3                               2.2.1
vtk                                   9.3.0
wheel                                 0.41.2
zipp                                  3.17.0

**Comment by aukselis-c1connections** [comment]
#1104

**Comment by PProfizi** [comment]
Hi @aukselis-c1connections,
As per the [compatibility table](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) could you please try upgrading to `ansys-dpf-core==0.10.1` and let me know if this persists please.

**Comment by aukselis-c1connections** [comment]
Hi @PProfizi, 

Thanks for a quick comeback. I have tried additionally with 0.10.1 and with 0.11.0, both yield the same outcome.

```

> Package                               Version     
> ------------------------------------- ------------
> ansys-api-mapdl                       0.5.1
> ansys-api-platform-instancemanagement 1.0.0
> ansys-dpf-core                        0.10.1
> ansys-mapdl-core                      0.65.0
> ansys-mapdl-reader                    0.53.0
> ansys-platform-instancemanagement     1.1.2
> ansys-tools-path                      0.4.0
> appdirs                               1.4.4
> cachetools                            5.3.3
> certifi                               2024.2.2
> charset-normalizer                    3.3.2
> click                                 8.1.7
> contourpy                             1.2.0
> cycler                                0.12.1
> fonttools                             4.45.1
> google-api-core                       2.17.1
> google-api-python-client              2.119.0
> google-auth                           2.28.1
> google-auth-httplib2                  0.2.0
> googleapis-common-protos              1.62.0
> grpcio                                1.62.0
> httplib2                              0.22.0
> idna                                  3.6
> imageio                               2.33.0
> importlib-metadata                    7.0.1
> importlib-resources                   6.1.1
> kiwisolver                            1.4.5
> matplotlib                            3.7.4
> numpy                                 1.26.4
> packaging                             23.2
> pandas                                2.1.3
> pexpect                               4.9.0
> Pillow                                10.1.0
> pip                                   23.3.1
> platformdirs                          4.0.0
> pooch                                 1.8.0
> protobuf                              3.20.3
> psutil                                5.9.8
> ptyprocess                            0.7.0
> pyansys-tools-versioning              0.5.0
> pyasn1                                0.5.1
> pyasn1-modules                        0.3.0
> pyiges                                0.3.1
> pyparsing                             3.1.1
> python-dateutil                       2.8.2
> pytz                                  2023.3.post1
> pyvista                               0.38.6
> PyYAML                                6.0.1
> requests                              2.31.0
> rsa                                   4.9
> scipy                                 1.10.1
> scooby                                0.9.2
> setuptools                            69.1.1
> six                                   1.16.0
> tqdm                                  4.66.2
> tzdata                                2023.3
> uritemplate                           4.1.1
> urllib3                               2.2.1
> vtk                                   9.3.0
> wheel                                 0.41.2
> zipp                                  3.17.0

```

```
DPF Server: {'server_ip': '', 'server_port': None, 'server_process_id': 51768, 'server_version': '7.1', 'os': 'posix'}
Traceback (most recent call last):
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/errors.py", line 101, in wrapper
    out = func(*args, **kwargs)
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 505, in result_info
    self._cache_result_info()
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 283, in _cache_result_info
    self._result_info = self._load_result_info()
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 430, in _load_result_info
    raise e
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 424, in _load_result_info
    result_info = op.get_output(0, types.result_info)
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/dpf_operator.py", line 494, in get_output
    parameters = {type_tuple[2]: type_tuple[1](self, pin)}
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/gate/generated/operator_capi.py", line 588, in operator_getoutput_result_info
    raise errors.DPFServerException(sError.value)
ansys.dpf.gate.errors.DPFServerException: ResultInfoProvider:2<-Data sources not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ansys/Desktop/./test.py", line 17, in <module>
    print(model)
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 203, in __str__
    txt += str(self.results)
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 157, in results
    self.metadata.result_info,
  File "/etc/environments/test/lib/python3.9/site-packages/ansys/dpf/core/errors.py", line 106, in wrapper
    raise DPFServerException(details)
ansys.dpf.gate.errors.DPFServerException: ResultInfoProvider:2<-Data sources not defined
```

**Comment by PProfizi** [comment]
Hi @aukselis-c1connections,
I see you are on Linux with the 241. Would it be possible for you to get and install the 241 Service Pack 1 from the [Ansys Customer Portal](https://support.ansys.com/)?

**Comment by aukselis-c1connections** [comment]
It's already with Service Pack 1

> Hi @aukselis-c1connections, I see you are on Linux with the 241. Would it be possible for you to get and install the 241 Service Pack 1 from the [Ansys Customer Portal](https://support.ansys.com/)?

```
2024 R1

Point Releases and Patches installed:

Ansys Service Pack 2024 R1.01
Ansys, Inc. License Manager 2024 R1
Ansys, Inc. License Manager 2024 R1.01
optiSLang 2024 R1
optiSLang 2024 R1.01
Remote Solve Manager Standalone Services 2024 R1
Remote Solve Manager Standalone Services 2024 R1.01
Structures 2024 R1
Structures 2024 R1.01
Additive 2024 R1
Additive 2024 R1.01
Aqwa 2024 R1
Aqwa 2024 R1.01
Autodyn 2024 R1
Autodyn 2024 R1.01
Customization Files for User Programmable Features 2024 R1
Customization Files for User Programmable Features 2024 R1.01
LS-DYNA 2024 R1
LS-DYNA 2024 R1.01
Mechanical Products 2024 R1
Mechanical Products 2024 R1.01
Motion 2024 R1
Motion 2024 R1.01
Sherlock 2024 R1
Sherlock 2024 R1.01
ACIS Geometry Interface 2024 R1
ACIS Geometry Interface 2024 R1.01
Catia, Version 5 Geometry Interface 2024 R1
Catia, Version 5 Geometry Interface 2024 R1.01
Parasolid Geometry Interface 2024 R1
Parasolid Geometry Interface 2024 R1.01
```

**Comment by kmahajan-cadfem** [comment]
@PProfizi, is there any known solution to this Problem?

**Comment by aukselis-c1connections** [comment]
@PProfizi, we still have this issue. Any updates on how to trouble shoot?
