### ISSUE TITLE
Error when trying to generate stress field animation of LS-Dyna result (d3plot)

### ISSUE THREAD

**Issue by Rfaelv** [ansys/pydpf-core#1615]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hi, everyone,

Whe I've reproduced the [06-animate_results.py](https://github.com/ansys/pydpf-core/blob/master/examples/06-plotting/06-animate_results.py) example for my Ls-Dyna result (.d3plot) to animate the stress field I got the following error on my end:

```python-traceback
Traceback (most recent call last):
  File "d:\Programacao\LS-Dyna\image_gerenator.py", line 55, in <module>
    stress_fields.animate()
  File "D:\Programacao\LS-Dyna\env\Lib\site-packages\ansys\dpf\core\fields_container.py", line 610, in animate
    return anim.animate(
           ^^^^^^^^^^^^^
  File "D:\Programacao\LS-Dyna\env\Lib\site-packages\ansys\dpf\core\animator.py", line 284, in animate
    return self._internal_animator.animate_workflow(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programacao\LS-Dyna\env\Lib\site-packages\ansys\dpf\core\animator.py", line 146, in animate_workflow
    render_frame(0)
  File "D:\Programacao\LS-Dyna\env\Lib\site-packages\ansys\dpf\core\animator.py", line 98, in render_frame
    self.add_field(
  File "D:\Programacao\LS-Dyna\env\Lib\site-packages\ansys\dpf\core\plotter.py", line 265, in add_field
    overall_data[ind] = field.data[mask]
                        ~~~~~~~~~~^^^^^^
IndexError: boolean index did not match indexed array along dimension 0; dimension is 46284 but corresponding boolean dimension is 15428
```

For the displacement field the animation was generated well. 

Can anyone, please, help me solve this problem?

### Steps To Reproduce

- Download my LS-Dyna results (d3plot):
[test.zip](https://github.com/user-attachments/files/15848753/test.zip)
- Run the following code:

```python
from ansys.dpf import core as dpf


ds = dpf.DataSources()
ds.set_result_file_path("test\d3plot", "d3plot")
model = dpf.Model(ds)

mesh_scoping = dpf.mesh_scoping_factory.nodal_scoping(model.metadata.meshed_region.nodes.scoping)
time_scoping = dpf.time_freq_scoping_factory.scoping_on_all_time_freqs(model)
stress_op = model.results.stress
stress_op = stress_op.on_time_scoping(time_scoping)
stress_op = stress_op.on_mesh_scoping(mesh_scoping)

stress_fields = stress_op.eval()
stress_fields.animate()
```

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2023 R2

### Which Python version causes the issue?

3.11

### Installed packages

ansys-dpf-core           0.12.2
cachetools               5.3.3
certifi                  2024.6.2
charset-normalizer       3.3.2
colorama                 0.4.6
contourpy                1.2.1
cycler                   0.12.1
fonttools                4.53.0
google-api-core          2.19.0
google-api-python-client 2.133.0
google-auth              2.30.0
google-auth-httplib2     0.2.0
googleapis-common-protos 1.63.1
grpcio                   1.64.1
httplib2                 0.22.0
idna                     3.7
imageio                  2.34.1
importlib_metadata       7.1.0
kiwisolver               1.4.5
matplotlib               3.9.0
numpy                    1.26.4
packaging                24.1
pillow                   10.3.0
pip                      23.2.1
platformdirs             4.2.2
pooch                    1.8.2
proto-plus               1.23.0
protobuf                 4.25.3
psutil                   5.9.8
pyasn1                   0.6.0
pyasn1_modules           0.4.0
pyparsing                3.1.2
python-dateutil          2.9.0.post0
pyvista                  0.43.9
requests                 2.32.3
rsa                      4.9
scooby                   0.10.0
setuptools               65.5.0
six                      1.16.0
tqdm                     4.66.4
uritemplate              4.1.1
urllib3                  2.2.1
vtk                      9.3.0
zipp                     3.19.2

**Comment by xiaolong-zjm** [comment]
我也出现了这个问题，输入的变量维度不匹配，针对lsdyna solid单元的应力动画提取没有官方案例，官方给的是shell的案例

**Comment by xiaolong-zjm** [comment]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 fieldsStr.animate(deform_by=disp,show_edges=False)

File [D:\python3913\lib\site-packages\ansys\dpf\core\fields_container.py:610](file:///D:/python3913/lib/site-packages/ansys/dpf/core/fields_container.py#line=609), in FieldsContainer.animate(self, save_as, deform_by, scale_factor, **kwargs)
    606 anim = Animator(workflow=wf, **kwargs)
    608 kwargs.setdefault("freq_kwargs", {"font_size": 12, "fmt": ".3e"})
--> 610 return anim.animate(
    611     loop_over=loop_over_field,
    612     save_as=save_as,
    613     scale_factor=scale_factor,
    614     **kwargs,
    615 )

File [D:\python3913\lib\site-packages\ansys\dpf\core\animator.py:284](file:///D:/python3913/lib/site-packages/ansys/dpf/core/animator.py#line=283), in Animator.animate(self, loop_over, output_name, input_name, save_as, scale_factor, freq_kwargs, **kwargs)
    282 if self.workflow is None:
    283     raise ValueError("Cannot animate without self.workflow.")
--> 284 return self._internal_animator.animate_workflow(
    285     loop_over=loop_over,
    286     workflow=self.workflow,
    287     output_name=output_name,
    288     input_name=input_name,
    289     save_as=save_as,
    290     scale_factor=scale_factor,
    291     freq_kwargs=freq_kwargs,
    292     **kwargs,
    293 )

File [D:\python3913\lib\site-packages\ansys\dpf\core\animator.py:146](file:///D:/python3913/lib/site-packages/ansys/dpf/core/animator.py#line=145), in _PyVistaAnimator.animate_workflow(self, loop_over, workflow, output_name, input_name, save_as, mode_number, scale_factor, **kwargs)
    143                 self._plotter.write_frame()
    145 # Write initial frame
--> 146 render_frame(0)
    147 # If not off_screen, enable the user to choose the camera position
    148 off_screen = kwargs.pop("off_screen", None)

File [D:\python3913\lib\site-packages\ansys\dpf\core\animator.py:98](file:///D:/python3913/lib/site-packages/ansys/dpf/core/animator.py#line=97), in _PyVistaAnimator.animate_workflow.<locals>.render_frame(frame)
     96 if "deform_by" in workflow.output_names:
     97     deform = workflow.get_output("deform_by", core.types.field)
---> 98 self.add_field(
     99     field,
    100     deform_by=deform,
    101     scale_factor_legend=scale_factor[frame],
    102     **kwargs,
    103 )
    104 kwargs_in = _sort_supported_kwargs(bound_method=self._plotter.add_text, **freq_kwargs)
    105 if mode_number is None:

File [D:\python3913\lib\site-packages\ansys\dpf\core\plotter.py:265](file:///D:/python3913/lib/site-packages/ansys/dpf/core/plotter.py#line=264), in _PyVistaPlotter.add_field(self, field, meshed_region, show_max, show_min, label_text_size, label_point_size, deform_by, scale_factor, scale_factor_legend, as_linear, **kwargs)
    263 if location != locations.overall:
    264     ind, mask = mesh_location.map_scoping(field.scoping)
--> 265     overall_data[ind] = field.data[mask]
    266 else:
    267     overall_data[:] = field.data[0]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3207 but corresponding boolean dimension is 1069

**Comment by PProfizi** [comment]
This issue may be a duplicate of https://github.com/ansys/pydpf-core/issues/1435.
I do not however have access to the test file shared anymore. It is empty when I download it.
Please reopen this issue if the fix for the other issue mentioned does not solve your problem.
