### ISSUE TITLE
PyPDF-Core

### ISSUE THREAD

**Issue by c-eriksson86** [ansys/pydpf-core#1776]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### Description of the bug

I tried to run the example:

from ansys.dpf import core as dpf
from ansys.dpf.core import examples
transient = examples.download_transient_result()
model = dpf.Model(transient)
model.metadata.meshed_region #FAILS!

The error message:

>>> model.metadata.meshed_region
Traceback (most recent call last):
  File "C:\Users\1990ChEr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ansys\dpf\core\errors.py", line 101, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\1990ChEr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ansys\dpf\core\model.py", line 464, in meshed_region
    self._meshed_region = self.mesh_provider.get_output(0, types.meshed_region)
  File "C:\Users\1990ChEr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ansys\dpf\core\dpf_operator.py", line 543, in get_output
    internal_obj = type_tuple[1](self, pin)
  File "C:\Users\1990ChEr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ansys\dpf\gate\generated\operator_capi.py", line 608, in operator_getoutput_meshed_region
    raise errors.DPFServerException(sError.value)
ansys.dpf.gate.errors.DPFServerException: MeshProvider:3<-Data sources not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\1990ChEr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ansys\dpf\core\errors.py", line 106, in wrapper
    raise DPFServerException(details)
ansys.dpf.gate.errors.DPFServerException: MeshProvider:3<-Data sources not defined

I have tried with my own .rst files and moved them to various places on the disk but still doesn't work.
Tested with python 3.9 and 3.10. 

### Steps To Reproduce

run the first example box from here: https://dpf.docs.pyansys.com/version/stable/api/ansys.dpf.core.model.html

 

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R2

### Which Python version causes the issue?

3.10

### Installed packages

ansys-api-mapdl                       0.5.2
ansys-api-platform-instancemanagement 1.1.0
ansys-dpf-core                        0.13.0
ansys-mapdl-core                      0.68.4
ansys-mapdl-reader                    0.54.1
ansys-math-core                       0.1.5
ansys-platform-instancemanagement     1.1.2
ansys-tools-path                      0.6.0
appdirs                               1.4.4
cachetools                            5.5.0
certifi                               2024.8.30
charset-normalizer                    3.3.2
click                                 8.1.7
colorama                              0.4.6
contourpy                             1.3.0
cycler                                0.12.1
fonttools                             4.54.1
geomdl                                5.3.1
google-api-core                       2.20.0
google-api-python-client              2.147.0
google-auth                           2.35.0
google-auth-httplib2                  0.2.0
googleapis-common-protos              1.65.0
grpcio                                1.66.1
httplib2                              0.22.0
idna                                  3.10
importlib_metadata                    8.5.0
kiwisolver                            1.4.7
matplotlib                            3.9.2
numpy                                 1.26.4
packaging                             24.1
pillow                                10.4.0
platformdirs                          4.3.6
pooch                                 1.8.2
proto-plus                            1.24.0
protobuf                              4.25.5
psutil                                6.0.0
pyansys-tools-versioning              0.6.0
pyasn1                                0.6.1
pyasn1_modules                        0.4.1
pyiges                                0.3.1
pyparsing                             3.1.4
python-dateutil                       2.9.0.post0
pyvista                               0.44.1
requests                              2.32.3
rsa                                   4.9
scipy                                 1.14.1
scooby                                0.10.0
six                                   1.16.0
tabulate                              0.9.0
tqdm                                  4.66.5
typing_extensions                     4.12.2
uritemplate                           4.1.1
urllib3                               2.2.3
vtk                                   9.3.1
zipp                                  3.20.2

**Comment by c-eriksson86** [comment]
works fine in a virtual environment so probably something was wrong with my locally installed packages. I'll close this one.
